# Generated by Django 4.2 on 2023-05-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='Hanoi', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0123456789', max_length=1000),
        ),
    ]
