# Generated by Django 4.2 on 2023-05-16 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
