# Generated by Django 4.1.7 on 2023-04-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_remove_order_book_remove_order_quantity_order_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
