# Generated by Django 4.1.7 on 2023-04-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_user_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='Hanoi', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0123456789', max_length=1000),
        ),
    ]
