# Generated by Django 4.1.7 on 2023-04-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0012_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sold_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
