# Generated by Django 4.1.7 on 2023-04-24 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0013_book_sold_quantity'),
        ('bookstore', '0013_order_user'),
    ]

    operations = [
    ]
