# Generated by Django 4.1.7 on 2023-04-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0014_merge_0013_book_sold_quantity_0013_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='user@gmail.com', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
