# Generated by Django 4.1.7 on 2023-04-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0015_user_email_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='user@gmail.com', max_length=100),
        ),
    ]
