# Generated by Django 4.1.7 on 2023-05-16 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0016_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='tel',
        ),
    ]
