# Generated by Django 4.1.7 on 2023-05-17 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0021_alter_book_cover'),
    ]

    operations = [
    ]
