# Generated by Django 4.1.7 on 2023-05-17 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0015_alter_order_user_alter_review_user_delete_user'),
        ('bookstore', '0022_merge_20230517_0900'),
    ]

    operations = [
    ]
